### ISSUE TITLE
Thống nhất ý tưởng, lựa chọn công nghệ

### ISSUE THREAD

**Issue by dangdinhtai0001** [dangdinhtai0001/Boarding-House#1]
Nêu ý kiến đi các bạn

**Comment by dangdinhtai0001** [comment]
Đã thống nhất là viết web app về quản lí khu trọ, giờ thì các bạn nêu xem con app của mình cần có những chức năng nào đây

**Comment by hant1607** [comment]
T nghĩ phải có mấy chức năng này:
-  Hiển tất cả các thông tin về nhà trọ, số phòng trọ, số phòng trống, số người ở trọ.
- Thêm, sửa, xóa người ở trọ
- Có mục quản lý hợp đồng giữa chủ trọ và người thuê
- Quản lý hóa đơn điện nước, các dịch vụ liên quan
- Gửi SMS khi đến hạn nộp tiền và cảnh báo khi đã quá thời hạn nộp tiền
Trước tiên là thế đã :))

**Comment by vuhuuson103** [comment]
Nên thêm phòng có những đồ dùng thiết yếu gì : điều hòa , nóng lạnh 
Thêm giá sinh hoạt : vệ sinh, điện nước

**Comment by hant1607** [comment]
À thêm cái chức năng phản hồi của khách thuê về cơ sở vật chất, kiểu như cái gì hỏng có thể liên hệ ngay với chủ trọ để sửa

**Comment by vuhuuson103** [comment]
Nếu quản lý dãy trọ mà to thì nên có phân quyền người dùng khi thuê quản lý , mà có khi làm nhiều chức năng quá k hết

**Comment by vuhuuson103** [comment]
có cần làm cái tên luôn k các bạn nhỉ  ✌️

**Comment by hant1607** [comment]
Tên app á?

**Comment by Trang3598** [comment]
hihi chào các cậu. H t mới thấy tn của các cậu. các c sôi nổi thế

**Comment by Trang3598** [comment]
khi thuê trọ người ta hay đòi xem phòng ý thì trong bảng dữ liệu t nghĩ cần có 1 cái button để khi click vào thì có ảnh và thông tin của phòng trọ ở đó .

**Comment by dangdinhtai0001** [comment]
này , để tránh loạn lên thì cho các ý kiến theo các chủ đề t đưa ra nhé , đầu tiên là con app này cho ai dùng , ý t là người thuê có đc vào hay ko ấy

**Comment by Trang3598** [comment]
sơn ơi ý m là phân quyền admin vs ng dùng ý à

**Comment by hant1607** [comment]
người thuê chỉ xem được thôi nhỉ?

**Comment by Trang3598** [comment]
tài nói cũng đúng để bàn sau vây ✌️

**Comment by dangdinhtai0001** [comment]
chốt khoản 1, App viết cho chủ trọ (Mọi quyền) và cho thằng người thuê vào xem mỗi phòng của nó và dịch vụ nhé :v

**Comment by Trang3598** [comment]
Thế Tài ơi thống nhất để m làm lead . Bh đã có ý tưởng rồi thì mk nên bắt đầu phân chia nhiệm vụ đi

**Comment by dangdinhtai0001** [comment]
:v mỗi thằng làm 1 cái kiểu yêu cầu rồi post lên đây, sau đó tổng hợp góp ra yêu cầu cuối cùng. Như thế đỡ loạn hơn.

**Comment by vuhuuson103** [comment]
[Ý TƯỞNG NHÓM CÔNG NGHỆ PHẦN MỀM.docx](https://github.com/dangdinhtai0001/Boarding-House/files/2461408/Y.T.NG.NHOM.CONG.NGH.PH.N.M.M.docx)
T tổng hợp lại mấy cái bọn m viết bên trên đấy

**Comment by hant1607** [comment]
Sau khi tổng hợp lại và t bổ sung thêm thì có yêu cầu như này:
- Với user là chủ nhà trọ :
•	Hiển tất cả các thông tin về nhà trọ, số phòng trọ, số phòng trống, số người ở trọ.
•	Thêm, sửa, xóa người ở trọ
•	Có mục quản lý hợp đồng giữa chủ trọ và người thuê, gửi SMS khi sắp hết hạn hợp đồng
•	Quản lý hóa đơn điện nước, các dịch vụ liên quan
•	Gửi SMS khi đến hạn nộp tiền và cảnh báo khi đã quá thời hạn nộp tiền
•	Thông tin cơ bản của các người thuê trọ
•	Đăng , thêm , sửa xóa các bài viết
•	Có mục để người thuê report về cơ sở vật chất nếu hỏng để chủ trọ sắp xếp sửa chữa
•	Quản lý thông tin về phương tiện đi lại của từng khách hàng.
- Với user là người thuê trọ:
•	Thông tin về phòng trọ của mình
•	Thông tin hợp đồng , giá dịch vụ
•	Nhận thông báo từ chủ nhà trọ
•	Trao đổi trực tiếp với chủ nhà trọ
- Phân quyền admin với người dùng : Chức năng login và có thêm phần đăng kí tài khoản để quản lí người dùng 
•	Trao đổi trực tiếp với người thuê trọ : Cửa số chat trực tuyến có thể bố sung chat tự động với những form câu hỏi giống nhau
•	Phân loại phòng trọ theo giá tiền cho người thuê dễ tìm hiểu : có thể là phòng trọ hay thuê căn hộ , thuê 1 phòng hay cả căn ấy
•	Ngoài ra còn có thể cho thêm 1 phần tìm người ở ghép nữa

**Comment by Trang3598** [comment]
t thấy như vậy là đầy đủ rồi đấy

**Comment by dangdinhtai0001** [comment]
Các chức năng :
	Đăng nhập (Chỉ chủ trọ và khách - cảm giác làm đc bằng facebook hay gmail thì làm 		bằng ko sẽ bỏ)
	Hiển thị tình trạng khu trọ ( số phòng đã thuê, số phòng còn trống)
	Hiển thị thông tin cho từng căn phòng
	Lưu trữ thông tin của người thuê
	Các thể loại dịch vụ (có thể thêm vào )
	Quản lí các luật khu tr
	Có khả năng nhận đặt phòng
	Quản lí hơp đồng cho thuê
	Báo cáo tình hình (...)
	Gửi email nhắc nhở về các đối tượng khi sắp đến hạn của sự kiện, thông báo mới gif 		đó
	Trao đổi trực tuyến giữa chủ và khách (Nghe mùi có vẻ khó)
	Có 1  dashboard dùng đăng bài

**Comment by dangdinhtai0001** [comment]
Chốt tính năng cho bản version 0.1 như này để đóng issue này nhé, chốt xong sẽ vẽ sang issue khác

**Comment by hant1607** [comment]
oke :))

**Comment by dangdinhtai0001** [comment]
Đã chốt tính năng cho version 0.1, h xem tính năng ở file read me nhánh Dev nhé :v: . Đóng issue.

**Comment by dangdinhtai0001** [comment]
Vì một số vấn đề khi làm đặc tả chức năng như là nhầm lẫn, các tính năng nhập nhằng với nhau nên mình cần xem lại về yêu cầu bài toán nhé ,

**Comment by hant1607** [comment]
T thấy nên làm như này:
- Quản lý phòng trọ
- Quản lý việc cho thuê phòng
- Quản lý khách trọ
- Quản lý dịch vụ
- Quản lý hợp đồng
- Quản lý hóa đơn hàng tháng(kèm gửi thông báo khi quá hạn nộp tiền phòng)
