### ISSUE TITLE
Đặc tả chức năng

### ISSUE THREAD

**Issue by dangdinhtai0001** [dangdinhtai0001/Boarding-House#2]
Ví dụ như màn hình gồm những nút nào, chữ nào, khi bấm vào nút này thì sang màn hình nào.....

**Comment by Trang3598** [comment]
cái này để tìm hiểu qua đã t chưa rõ lắm

**Comment by dangdinhtai0001** [comment]
Cuối tuần tất cả gửi bản đặc tả chức năng nhé :v

**Comment by hant1607** [comment]
Sơn ơi m làm 4 chức năng đầu. mấy cái còn lại t vs trang chia nhau làm nhé :))

**Comment by vuhuuson103** [comment]
đồng ý , vậy t làm 4 cái đầu

**Comment by hant1607** [comment]
Cái chức năng đặt phòng tức là xem chi tiết phòng rồi đặt chỗ để đến xem phòng trực tiếp à cm?

**Comment by dangdinhtai0001** [comment]
nó là xem phòng còn trống không, nếu có khách đặt thì trả ra phòng đó cho khách quyết, nếu ko còn phòng thì báo ko, khách chỉ cần xem thông tin phòng thôi, ko nhất thiết phải đặt luôn

**Comment by hant1607** [comment]
À, hiểu rồi. Mà còn cái luật cho phòng trọ nữa, t chả biết viết gì :((, có nên cho cái button report để khách hàng báo cáo những luật vớ vẩn k nhỉ?

**Comment by dangdinhtai0001** [comment]
ko , luật thì để trống cũng đc, để sau này thêm luạt sau tùy theo hoàn cảnh chứ

**Comment by hant1607** [comment]
Bản demo 5 chức năng t làm đây nhé(t thấy hình như mình thiếu chức năng in hóa đơn nên t làm luôn)
Mọi người xem thế nào, cần sửa gì không
[DacTaChucNang_Ha.docx](https://github.com/dangdinhtai0001/Boarding-House/files/2475108/DacTaChucNang_Ha.docx)

**Comment by vuhuuson103** [comment]
[DacTaChucNang-Son.docx](https://github.com/dangdinhtai0001/Boarding-House/files/2475437/DacTaChucNang-Son.docx)
cái hiển thị thông tin phòng trọ với cái quản lý xem số phòng nên cho vào cùng 1 cái . Có gì xem lại t sửa nhé

**Comment by Trang3598** [comment]
[Phân tích thiết kế hệ thống.docx](https://github.com/dangdinhtai0001/Boarding-House/files/2476268/Phan.tich.thi.t.k.h.th.ng.docx)
tạm thời thế này đã ✌️

**Comment by dangdinhtai0001** [comment]
:v sao t đọc các bản mô tả mà ko hiểu gì vậy trời

**Comment by vuhuuson103** [comment]
vẽ lược đồ activity à

**Comment by dangdinhtai0001** [comment]
vẽ biểu đồ ca sử dụng nhé, activity chắc để ngày hôm sau

**Comment by hant1607** [comment]
ờ, thế Sơn m vẽ những cái nào nào?

**Comment by Trang3598** [comment]
lần này giao diện bn t chọn qua qua xong chỉnh lại m thấy chỗ nào k vừa mắt nhớ bảo

**Comment by Trang3598** [comment]
mà giao diện cũng k làm nhanh dc đâu

**Comment by dangdinhtai0001** [comment]
Lul, t bảo là cuối tuần chốt template thôi, chưa phải giao diện, lagm như này t thấy là nhẹ nhàng lắm rồi ấy

**Comment by Trang3598** [comment]
sơn ơi m làm 3 cái đầu t vs hà chia nhau làm 5 cái cuối nhá ✌️

**Comment by Trang3598** [comment]
hôm nay github bị sao ý nhỉ k load dc cmt mới ý

**Comment by hant1607** [comment]
![quanlyphong](https://user-images.githubusercontent.com/43999134/47305799-cf668700-d654-11e8-8c5b-14cd4db516fd.png)
Biểu đồ use case quản lý phòng

**Comment by hant1607** [comment]
Use case Quản lý dịch vụ
![quanlydichvu](https://user-images.githubusercontent.com/43999134/47305850-f8871780-d654-11e8-9abf-3b25c22ff957.png)

**Comment by hant1607** [comment]
Use case Quản lý thuê dịch vụ
![quanlythuedichvu](https://user-images.githubusercontent.com/43999134/47305868-06d53380-d655-11e8-97e8-7a6c4ad9cdb3.png)

**Comment by hant1607** [comment]
Cm xem thế nào, xem cần sửa k?

**Comment by Trang3598** [comment]
Lập báo cáo
![l p bao cao](https://user-images.githubusercontent.com/38637027/47306258-1e60ec00-d656-11e8-8e7c-e64e4791beaa.jpg)

**Comment by Trang3598** [comment]
Quản lý tài khoản
![quanlitaikhoan](https://user-images.githubusercontent.com/38637027/47306314-43555f00-d656-11e8-94e0-afcd585d3ebd.jpg)

**Comment by Trang3598** [comment]
Vẽ hơi xấu tí nhá :p Các mày ngủ  ngon t buồn ngủ quá rồi

**Comment by hant1607** [comment]
Thế 3 đứa chia nhau ra lm thôi.

Vào 21:30, Th 2, 22 thg 10, 2018 dangdinhtai0001 <notifications@github.com>
đã viết:

**Comment by vuhuuson103** [comment]
![qu n ly thue phong](https://user-images.githubusercontent.com/43998891/47434208-45d9c500-d7cc-11e8-81e9-f4d80feb31df.png)
Quản lý thuê phòng
![qu n ly thue phong](https://user-images.githubusercontent.com/43998891/47434218-512cf080-d7cc-11e8-9ea1-23fdee9f6bcf.png)

**Comment by vuhuuson103** [comment]
![qu n ly khach hang](https://user-images.githubusercontent.com/43998891/47434259-67d34780-d7cc-11e8-9c1f-5a1378a77328.png)
Quản lý khách hàng

**Comment by vuhuuson103** [comment]
[
![l p hoa d n h p d ng](https://user-images.githubusercontent.com/43998891/47434317-889b9d00-d7cc-11e8-9504-e14851988de8.png)
](url)
Lập hóa đơn , hợp đồng

**Comment by vuhuuson103** [comment]
các mày xem lại giúp mình với nhé , xin lỗi vì sự chậm trễ này :)))

**Comment by Trang3598** [comment]
mời lead phát biểu cái xem hài lòng hay chưa :v
