### ISSUE TITLE
Thiết kế database

### ISSUE THREAD

**Issue by dangdinhtai0001** [dangdinhtai0001/Boarding-House#4]
Tài thiết kế database

**Comment by dangdinhtai0001** [comment]
Tình hình là lúc tạo database t bị lỗi chô tạo dịch vụ nên phải hoãn database lại nhé

**Comment by dangdinhtai0001** [comment]
[boardinghouse (2).zip](https://github.com/dangdinhtai0001/Boarding-House/files/2515955/boardinghouse.2.zip)

đã xong db nhé

**Comment by Trang3598** [comment]
Tài ơi ví dụ các thuộc tính như gender vs lại status sao ko để kiểu bit ấy cho dễ

**Comment by hant1607** [comment]
Trong bảng hom_rental ấy, cái customerID phải điền đủ số người thuê phòng tương ứng vs phòng đấy à, hay mỗi phòng chỉ cần 1 đại diện thôi

**Comment by dangdinhtai0001** [comment]
Chụp lại t xem cái, hình như chỗ đó đáng ra là 1-n mà t để 1 1 mất rồi

**Comment by Trang3598** [comment]
có ai thấy cái bảng contract nó sao k nhỉ ?

**Comment by Trang3598** [comment]
![image](https://user-images.githubusercontent.com/38637027/47953935-90222980-dfb6-11e8-9b5c-1febc28c6be9.png)
nếu như nầy mỗi lần thêm dc 1 dịch vụ thôi à

**Comment by dangdinhtai0001** [comment]
1 người thuê đc nhiều phòng

**Comment by dangdinhtai0001** [comment]
Type hình như là loại phòng

**Comment by Trang3598** [comment]
![image](https://user-images.githubusercontent.com/38637027/47954129-28b9a900-dfb9-11e8-9f2f-02fc600fea8f.png)

**Comment by Trang3598** [comment]
[quanlynhatro.zip](https://github.com/dangdinhtai0001/Boarding-House/files/2548496/quanlynhatro.zip)
Bản db đã đổ dữ liệu vào đây nhé . Nếu thấy hơi ít thì bảo t đổ thêm cũng được

**Comment by hant1607** [comment]
ơ mà hình như chưa có bảng hóa đơn phải không nhỉ?

**Comment by dangdinhtai0001** [comment]
đổ dữ liệu bị nhầm rồi nhé, bảng home là bảng để lưu duy nhất bản ghi về boss của toàn nhà trọ thôi

**Comment by Trang3598** [comment]
v để t sửa lại

**Comment by dangdinhtai0001** [comment]
không cần đâu, cái đó ko quan trọng 
cái này để tạm đó đã 
bây giờ cần test cái t nói hôm chiều T2 ấy

**Comment by dangdinhtai0001** [comment]
có 1 số vấn đề nữa là :v t quên mất môt số thuộc tính của phòng: Cần thêm diện tích(int), khép kín(boolean), nhà tắm (int) , cửa sổ (int),... cần thêm gì nữa ko ấy nhỉ >?

**Comment by Trang3598** [comment]
thôi k cần miêu tả kĩ thế đâu thay vì ấy m cho trường image vào đỡ tốn cột :p

**Comment by Trang3598** [comment]
tài ơi cho t hỏi lại tí quên mất rồi test cái gì ấy nhỉ

**Comment by Trang3598** [comment]
t vs hà đang chuẩn bị làm giao diện đây . À test sản phẩm t nhớ ra rồi

**Comment by dangdinhtai0001** [comment]
vì trên cái giao diện hôm trước chọn cần truy ra đống đấy nên phải có
