### ISSUE TITLE
Chọn giao diện

### ISSUE THREAD

**Issue by dangdinhtai0001** [dangdinhtai0001/Boarding-House#5]
Chỉ cần chọn xem nó trông ntn thôi :v chưa cần code đâu :v

**Comment by dangdinhtai0001** [comment]
:v nốt tuần nhé các bạn :v

**Comment by Trang3598** [comment]
ok ok =)))

**Comment by vuhuuson103** [comment]
gần cuối tuần rồi các bạn trẻ :v

**Comment by dangdinhtai0001** [comment]
3 bạn chia ra để thiết kế các màn hình chức năng nhé ,

**Comment by dangdinhtai0001** [comment]
https://colorlib.com/wp/template/bluesky/ 
vốt 1 cái , chọn cái nữa đi các bạn ;v

**Comment by Trang3598** [comment]
tưởng cần như này thôi ô ơi ✌️ 
https://colorlib.com//polygon/admindek/default/index.html

**Comment by hant1607** [comment]
t thấy cái này đẹp hơn cái m tìm mà Trang -.-
https://colorlib.com/polygon/gentelella/index3.html

**Comment by hant1607** [comment]
hoặc cái này mà để hiển thị phòng cũng đẹp nè
https://pixelhint.com/demo/la_casa/

**Comment by Trang3598** [comment]
như nhau =))

**Comment by Trang3598** [comment]
cái dưới của m xấu như kiểu đi du lịch chứ kp đi cho thuê trọ :v

**Comment by Trang3598** [comment]
vs lại hiệu ứng kém

**Comment by dangdinhtai0001** [comment]
giao diện đâu các bạn trẻ

**Comment by hant1607** [comment]
log in á?mà template đã chốt đc đâu -.-

**Comment by vuhuuson103** [comment]
https://colorlib.com/etc/lf/Login_v5/index.html

**Comment by dangdinhtai0001** [comment]
sắp cuối tuần cmnr, t giục dần ko đến khi lại "...t bận đi chơi..."  thì vỡ mồm

**Comment by hant1607** [comment]
yên tâm, cuối tuần này k có lịch gì cả :v

**Comment by hant1607** [comment]
t thấy cái login này ok này
![image](https://user-images.githubusercontent.com/43999134/47444779-7415cf80-d7e1-11e8-9589-f3d4b6920ae6.png)

**Comment by vuhuuson103** [comment]
![image](https://user-images.githubusercontent.com/43998891/47444910-c820b400-d7e1-11e8-9640-81af25e9325c.png)

**Comment by hant1607** [comment]
cái của t đẹp hơn -.-

**Comment by vuhuuson103** [comment]
cái của t nó dễ thương hơn

**Comment by vuhuuson103** [comment]
file:///C:/Users/VuHuuSon/AppData/Local/Temp/Rar$EXa0.921/pages/samples/login.html

**Comment by vuhuuson103** [comment]
![image](https://user-images.githubusercontent.com/43998891/47445132-614fca80-d7e2-11e8-8d2d-cc98483376e6.png)

**Comment by hant1607** [comment]
cái này k có đăng nhập bằng fb các thứ, cái của t ok rồi ✌️

**Comment by vuhuuson103** [comment]
nhìn nó hơi u ám , nhưng cũng k phải xấu lắm có thể dùng được :)))

**Comment by hant1607** [comment]
-.-, chắc đổi nền đc

**Comment by Trang3598** [comment]
t thấy cái nào đủ chức năng trong đặc tả của mk là được độ đẹp hay không t thấy k cần phải so đo lắm đâu -_-

**Comment by Trang3598** [comment]
t vote cái giao diện của hà đầy đủ chức năng nhưng phải chỉnh lại 1 ít

**Comment by hant1607** [comment]
zê ✌️

**Comment by Trang3598** [comment]
https://colorlib.com/etc/lf/Login_v5/index.html
t thích đơn giản như này thôi  :v

**Comment by vuhuuson103** [comment]
đấy t vừa đăng cái ý lên mà Trang , con Hà nó chê xấu

**Comment by hant1607** [comment]
chả à :v

**Comment by vuhuuson103** [comment]
không thì lấy cái kia cũng được xong đổi quả ảnh này vào cho nó giống cái app thuê trọ
![thiet_ke_phong_tro_nho_dep-700x340](https://user-images.githubusercontent.com/43998891/47446241-07043900-d7e5-11e8-8858-195f4183d1d6.jpg)

**Comment by Trang3598** [comment]
quên mải lướt :v

**Comment by Trang3598** [comment]
thế thay ảnh vào cũng dc nhưng phải full HD ms được

**Comment by hant1607** [comment]
các cậu có thích thế này k :v
![image](https://user-images.githubusercontent.com/43999134/47446383-50548880-d7e5-11e8-9ad8-de9c8703ab53.png)

**Comment by Trang3598** [comment]
con hà thôi ảnh trai nhá làm việc nghiêm túc -_-

**Comment by Trang3598** [comment]
@dangdinhtai0001  chọn đi bạn bạn thích mấy kiểu này hay ko :v

**Comment by hant1607** [comment]
nào chốt đc template thì mình lựa cái ảnh nào màu phù hợp đổi là đc

**Comment by dangdinhtai0001** [comment]
T vote cái thằng sơn chê tôi :v

**Comment by dangdinhtai0001** [comment]
Bỏ cái login bằng mạng xã hội nhé

**Comment by hant1607** [comment]
S thế? V chọn cái nào 😑

**Comment by dangdinhtai0001** [comment]
@vuhuuson103 lấy cái này nhé

**Comment by Trang3598** [comment]
Chốt đi cm ơi

**Comment by hant1607** [comment]
login t thích cái này nè
![image](https://user-images.githubusercontent.com/43999134/47514100-c6222800-d8a9-11e8-865e-adaede163f1a.png)

**Comment by hant1607** [comment]
để t đổi cái background đẹp đẹp xem thế nào

**Comment by Trang3598** [comment]
https://p.w3layouts.com/demos_new/template_demo/12-04-2018/effect_login_form-demo_Free/404133165/web/index.html
đây các bạn ơi đẹp ơi là đẹp

**Comment by hant1607** [comment]
cũng đc đấy

**Comment by Trang3598** [comment]
https://colorlib.com//polygon/admindek/default/index.html

**Comment by vuhuuson103** [comment]
https://github.com/puikinsh/sufee-admin-dashboard

**Comment by vuhuuson103** [comment]
https://github.com/almasaeed2010/AdminLTE

**Comment by dangdinhtai0001** [comment]
chốt xong giao diện, chuyển sáng test db
